### PR TITLE
Remove unmaintained and replace with new maintainers

### PR DESCRIPTION
**Pull request by robvdl**
List current maintainers in a new section

### CODE REVIEW

**Comment by robvdl** [comment]
@nkabir are you OK with having your name under under new maintainers?

@hsoft or @ellmetha are you OK with the new maintainers / original authors section.

**Comment by nkabir** [comment]
Sure. I can help with code reviews and bug triage.

**Comment by robvdl** [comment]
There's been a bit happening lately, we finally got the CI pipeline unclogged by using the LXD snap and also have a vagrant setup for running the tests locally.  There's some work underway to redo the user id mapping of shares using raw.idmap and I am about to put up a commit to mark this version 0.5.0dev, some of that stuff is already merged but it isn't complete yet.  There are a few minor things deprecated from the config file and I will be documenting this before 0.5 gets released.

**Comment by ellmetha** [comment]
@robvdl 👍

**Pull request merged**
