### PR TITLE
Allow different types of SSH keys

### LINKED ISSUE #165: SSH keys with other algorithms should be supported
Currently, SSH key deployment into the container uses a hardcoded key name (`~/.ssh/id_rsa.pub`). Thus keys using another algorithm (ed25519, ecdsa) are not detected.

### PR DESCRIPTION
**Pull request by mtausig**
This should fix #165.
Unfortunately, I haven't been able to properly test it on my system due to issue #161 .

### CODE REVIEW

**Comment by robvdl** [comment]
what about id_dsa.pub

**Comment by mtausig** [comment]
Since DSA is very much deprecated, I decided against including it.
But if you prefer, I can add it.

**Comment by robvdl** [comment]
I see, I'm not sure then. We can leave it out and if anyone asks we just mention dsa keys are deprecated.

**Comment by mtausig** [comment]
I can add a comment.
BTW: Is there something like a recommended dev environment for new contributors to get the current master branch actually running. I'd like to test this myself.

**Comment by robvdl** [comment]
Well we created a simple Vagrantfile for basic testing of the application a year or so ago, it's nothing too fancy but we used it for testing in the past as I recall.

It's been a long time since I've worked on this project at all though, so can't say if it still works now.

**Comment by mtausig** [comment]
Comment added & tested (at least manually).

This is finished IMO.

**Pull request merged**
